version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./casc:/var/jenkins_home/casc
      - ./jobs:/var/jenkins_home/jobs

volumes:
  jenkins_home:
